name: Sync-Python-Actions.GoodInfo.Analyzer
on:
  workflow_dispatch:
  push:
     branches:
       - main
     paths:
       - raw_conceptstock_daily.csv
       - raw_conceptstock_weekly.csv
       - raw_conceptstock_monthly.csv

jobs:
  sync-backup-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Sync up
        uses: BetaHuhn/repo-file-sync-action@latest
        with:
          GH_PAT: ${{ secrets.REPO_FILE_SYNC_WENCHIEHLEE_INVESTMENT }}
          CONFIG_PATH: .github/sync-Python-Actions.GoodInfo.Analyzer.yml
          COMMIT_EACH_FILE: false
          PR_LABELS: "automated-sync"
          SKIP_PR: true
